version: '3.8'
services:
  drinktionary:
    image: drinktionary
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8091:8091
    networks:
      - eureka-network
networks:
  eureka-network:
    driver: bridge