server:
  port: 8091
  servlet:
    context-path: /drinks

spring:
  application:
    name: drinktionary
  datasource:
    url: jdbc:mysql://sunjoo-drinktionary.clau8wyu484y.ap-northeast-2.rds.amazonaws.com:3306/sunjoo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: drinktionary0606
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sunjoo-server-eureka-eureka-1:8761/eureka/